//! Known-Answer Test (KAT) verification.
//!
//! Loads `tests/kat_vectors.json` (generated by `cargo run --bin gen_kat`)
//! and verifies every vector against the current implementation.
//!
//! Any code change that alters a primitive's output will cause a failure here,
//! providing automatic regression detection.

use serde::Deserialize;
use std::fs;

fn from_hex(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

// ── Deserialization types ─────────────────────────────────────────

#[derive(Deserialize)]
struct KatVectors {
    #[allow(dead_code)]
    version: String,
    spin_hash: Vec<HashVector>,
    spin_kdf: Vec<KdfVector>,
    aead: Vec<AeadVector>,
    sponge: Vec<SpongeVector>,
    kem: Vec<KemVector>,
}

#[derive(Deserialize)]
struct HashVector {
    description: String,
    input_hex: String,
    output_hex: String,
}

#[derive(Deserialize)]
struct KdfVector {
    description: String,
    key_hex: String,
    salt_hex: String,
    info_ascii: String,
    length: usize,
    output_hex: String,
}

#[derive(Deserialize)]
struct AeadVector {
    description: String,
    key_hex: String,
    nonce_hex: String,
    aad_hex: String,
    plaintext_hex: String,
    ciphertext_hex: String,
    tag_hex: String,
}

#[derive(Deserialize)]
struct SpongeVector {
    description: String,
    input_hex: String,
    squeeze_len: usize,
    output_hex: String,
}

#[derive(Deserialize)]
struct KemVector {
    description: String,
    #[allow(dead_code)]
    level: String,
    #[allow(dead_code)]
    pk_hex: String,
    sk_hex: String,
    ct_hex: String,
    ss_hex: String,
}

fn load_vectors() -> KatVectors {
    let json = fs::read_to_string("tests/kat_vectors.json")
        .expect("tests/kat_vectors.json not found — run `cargo run --bin gen_kat` first");
    serde_json::from_str(&json).expect("failed to parse KAT vectors")
}

// ── Tests ─────────────────────────────────────────────────────────

#[test]
fn kat_spin_hash() {
    let vectors = load_vectors();
    for v in &vectors.spin_hash {
        let input = from_hex(&v.input_hex);
        let expected = from_hex(&v.output_hex);
        let actual = qs_crypto::spin_hash(&input);
        assert_eq!(
            actual.as_slice(),
            expected.as_slice(),
            "spin_hash mismatch: {}",
            v.description
        );
    }
}

#[test]
fn kat_spin_kdf() {
    let vectors = load_vectors();
    for v in &vectors.spin_kdf {
        let key = from_hex(&v.key_hex);
        let salt = from_hex(&v.salt_hex);
        let actual = qs_crypto::spin_kdf(&key, &salt, v.info_ascii.as_bytes(), v.length);
        let expected = from_hex(&v.output_hex);
        assert_eq!(actual, expected, "spin_kdf mismatch: {}", v.description);
    }
}

#[test]
fn kat_aead() {
    let vectors = load_vectors();
    for v in &vectors.aead {
        let key: [u8; 32] = from_hex(&v.key_hex).try_into().unwrap();
        let nonce: [u8; 16] = from_hex(&v.nonce_hex).try_into().unwrap();
        let aad = from_hex(&v.aad_hex);
        let plaintext = from_hex(&v.plaintext_hex);
        let expected_ct = from_hex(&v.ciphertext_hex);
        let expected_tag: [u8; 16] = from_hex(&v.tag_hex).try_into().unwrap();

        // Verify encryption produces expected ciphertext + tag
        let result = qs_crypto::aead::encrypt(&key, &nonce, &aad, &plaintext);
        assert_eq!(
            result.ciphertext, expected_ct,
            "aead encrypt ciphertext mismatch: {}",
            v.description
        );
        assert_eq!(
            result.tag, expected_tag,
            "aead encrypt tag mismatch: {}",
            v.description
        );

        // Verify decryption roundtrip
        let decrypted = qs_crypto::aead::decrypt(&key, &nonce, &aad, &expected_ct, &expected_tag)
            .expect("aead decrypt must succeed for KAT vector");
        assert_eq!(
            decrypted, plaintext,
            "aead decrypt mismatch: {}",
            v.description
        );
    }
}

#[test]
fn kat_sponge() {
    let vectors = load_vectors();
    let params = qs_crypto::params::Params::default();
    for v in &vectors.sponge {
        let input = from_hex(&v.input_hex);
        let expected = from_hex(&v.output_hex);

        let mut sponge = qs_crypto::SpinSponge::new(&params);
        sponge.absorb(&input);
        let actual = sponge.squeeze_raw(v.squeeze_len);
        assert_eq!(actual, expected, "sponge mismatch: {}", v.description);
    }
}

#[test]
fn kat_kem_decaps() {
    let vectors = load_vectors();
    for v in &vectors.kem {
        let sk_bytes = from_hex(&v.sk_hex);
        let ct_bytes = from_hex(&v.ct_hex);
        let expected_ss = from_hex(&v.ss_hex);

        let sk = qs_crypto::kem::types::PrivateKey::from_bytes(&sk_bytes)
            .expect("invalid SK in KAT vector");
        let ct = qs_crypto::kem::types::Ciphertext::from_bytes(&ct_bytes)
            .expect("invalid CT in KAT vector");

        let ss = qs_crypto::decapsulate(&sk, &ct).expect("decaps must succeed for KAT vector");
        assert_eq!(
            ss.as_bytes().as_slice(),
            expected_ss.as_slice(),
            "kem decaps mismatch: {}",
            v.description
        );
    }
}
